/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author Arkynes
 */
public class Request extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Request.class.getName());

    /**
     * Creates new form Request
     */
    public Request() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestPage = new javax.swing.JPanel();
        ContentHolder = new SystemOtherComps.PH_Panel();
        pH_Panel1 = new SystemOtherComps.PH_Panel();
        pH_Label4 = new SystemOtherComps.PH_Label();
        pH_Panel6 = new SystemOtherComps.PH_Panel();
        pH_Label6 = new SystemOtherComps.PH_Label();
        pH_Label7 = new SystemOtherComps.PH_Label();
        pH_Panel7 = new SystemOtherComps.PH_Panel();
        pH_Panel8 = new SystemOtherComps.PH_Panel();
        pH_Label8 = new SystemOtherComps.PH_Label();
        pH_Panel2 = new SystemOtherComps.PH_Panel();
        pH_Panel3 = new SystemOtherComps.PH_Panel();
        pH_Label2 = new SystemOtherComps.PH_Label();
        pH_Label5 = new SystemOtherComps.PH_Label();
        pH_Panel4 = new SystemOtherComps.PH_Panel();
        pH_Panel5 = new SystemOtherComps.PH_Panel();
        pH_Label3 = new SystemOtherComps.PH_Label();
        pH_Label9 = new SystemOtherComps.PH_Label();
        pH_Button1 = new SystemOtherComps.PH_Button();
        pH_Panel9 = new SystemOtherComps.PH_Panel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        pH_Label1 = new SystemOtherComps.PH_Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RequestPage.setBackground(new java.awt.Color(239, 231, 218));
        RequestPage.setPreferredSize(new java.awt.Dimension(1001, 680));

        ContentHolder.setBackground(new java.awt.Color(245, 240, 234));
        ContentHolder.setAAA_ImageBoundArcSize(40);
        ContentHolder.setAAA_roundBottomLeft(40);
        ContentHolder.setAAA_roundBottomRight(40);
        ContentHolder.setAAA_roundTopLeft(40);
        ContentHolder.setAAA_roundTopRight(40);
        ContentHolder.setAA_ArcSize(40);
        ContentHolder.setAA_BorderColor(new java.awt.Color(137, 100, 71));
        ContentHolder.setAA_DrawBorder(true);

        pH_Panel1.setBackground(new java.awt.Color(245, 240, 234));
        pH_Panel1.setAAA_roundBottomLeft(40);

        pH_Label4.setForeground(new java.awt.Color(72, 53, 40));
        pH_Label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label4.setText("REQUEST FORM");
        pH_Label4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N

        pH_Panel6.setBackground(new java.awt.Color(245, 240, 234));
        pH_Panel6.setAAA_ImageBoundArcSize(30);
        pH_Panel6.setAAA_roundBottomLeft(30);
        pH_Panel6.setAAA_roundBottomRight(30);
        pH_Panel6.setAAA_roundTopLeft(30);
        pH_Panel6.setAAA_roundTopRight(30);
        pH_Panel6.setAA_ArcSize(30);
        pH_Panel6.setAA_BorderColor(new java.awt.Color(72, 53, 40));
        pH_Panel6.setAA_DrawBorder(true);

        javax.swing.GroupLayout pH_Panel6Layout = new javax.swing.GroupLayout(pH_Panel6);
        pH_Panel6.setLayout(pH_Panel6Layout);
        pH_Panel6Layout.setHorizontalGroup(
            pH_Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pH_Panel6Layout.setVerticalGroup(
            pH_Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pH_Label6.setForeground(new java.awt.Color(72, 53, 40));
        pH_Label6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label6.setText("PHONE NUMBER :");
        pH_Label6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N

        pH_Label7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label7.setText("EMAIL ADDRESS :");
        pH_Label7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N

        pH_Panel7.setBackground(new java.awt.Color(245, 240, 234));
        pH_Panel7.setAAA_ImageBoundArcSize(30);
        pH_Panel7.setAAA_roundBottomLeft(30);
        pH_Panel7.setAAA_roundBottomRight(30);
        pH_Panel7.setAAA_roundTopLeft(30);
        pH_Panel7.setAAA_roundTopRight(30);
        pH_Panel7.setAA_ArcSize(30);
        pH_Panel7.setAA_BorderColor(new java.awt.Color(72, 53, 40));
        pH_Panel7.setAA_DrawBorder(true);

        javax.swing.GroupLayout pH_Panel7Layout = new javax.swing.GroupLayout(pH_Panel7);
        pH_Panel7.setLayout(pH_Panel7Layout);
        pH_Panel7Layout.setHorizontalGroup(
            pH_Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pH_Panel7Layout.setVerticalGroup(
            pH_Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pH_Panel8.setBackground(new java.awt.Color(245, 240, 234));
        pH_Panel8.setAAA_ImageBoundArcSize(30);
        pH_Panel8.setAAA_roundBottomLeft(30);
        pH_Panel8.setAAA_roundBottomRight(30);
        pH_Panel8.setAAA_roundTopLeft(30);
        pH_Panel8.setAAA_roundTopRight(30);
        pH_Panel8.setAA_ArcSize(30);
        pH_Panel8.setAA_BorderColor(new java.awt.Color(72, 53, 40));
        pH_Panel8.setAA_DrawBorder(true);

        javax.swing.GroupLayout pH_Panel8Layout = new javax.swing.GroupLayout(pH_Panel8);
        pH_Panel8.setLayout(pH_Panel8Layout);
        pH_Panel8Layout.setHorizontalGroup(
            pH_Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pH_Panel8Layout.setVerticalGroup(
            pH_Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pH_Label8.setForeground(new java.awt.Color(72, 53, 40));
        pH_Label8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label8.setText("FULL NAME :");
        pH_Label8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N

        javax.swing.GroupLayout pH_Panel1Layout = new javax.swing.GroupLayout(pH_Panel1);
        pH_Panel1.setLayout(pH_Panel1Layout);
        pH_Panel1Layout.setHorizontalGroup(
            pH_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pH_Panel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(pH_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pH_Panel8, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(pH_Label7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(pH_Label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pH_Panel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(pH_Label8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pH_Label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pH_Panel7, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addContainerGap())
        );
        pH_Panel1Layout.setVerticalGroup(
            pH_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pH_Panel1Layout.createSequentialGroup()
                .addComponent(pH_Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Panel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Panel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pH_Panel2.setBackground(new java.awt.Color(245, 240, 234));

        javax.swing.GroupLayout pH_Panel2Layout = new javax.swing.GroupLayout(pH_Panel2);
        pH_Panel2.setLayout(pH_Panel2Layout);
        pH_Panel2Layout.setHorizontalGroup(
            pH_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );
        pH_Panel2Layout.setVerticalGroup(
            pH_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pH_Panel3.setBackground(new java.awt.Color(245, 240, 234));
        pH_Panel3.setAAA_roundBottomRight(40);
        pH_Panel3.setAAA_roundTopRight(40);

        pH_Label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label2.setText("ART STYLE (CATEGORY)");
        pH_Label2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        pH_Label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label5.setText("DEADLINE");
        pH_Label5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        pH_Panel4.setBackground(new java.awt.Color(245, 240, 234));
        pH_Panel4.setAAA_ImageBoundArcSize(30);
        pH_Panel4.setAAA_roundBottomLeft(30);
        pH_Panel4.setAAA_roundBottomRight(30);
        pH_Panel4.setAAA_roundTopLeft(30);
        pH_Panel4.setAAA_roundTopRight(30);
        pH_Panel4.setAA_ArcSize(30);
        pH_Panel4.setAA_BorderColor(new java.awt.Color(137, 100, 71));
        pH_Panel4.setAA_DrawBorder(true);
        pH_Panel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout pH_Panel4Layout = new javax.swing.GroupLayout(pH_Panel4);
        pH_Panel4.setLayout(pH_Panel4Layout);
        pH_Panel4Layout.setHorizontalGroup(
            pH_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        pH_Panel4Layout.setVerticalGroup(
            pH_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        pH_Panel5.setBackground(new java.awt.Color(245, 240, 234));
        pH_Panel5.setAAA_ImageBoundArcSize(30);
        pH_Panel5.setAAA_roundBottomLeft(30);
        pH_Panel5.setAAA_roundBottomRight(30);
        pH_Panel5.setAAA_roundTopLeft(30);
        pH_Panel5.setAAA_roundTopRight(30);
        pH_Panel5.setAA_ArcSize(30);
        pH_Panel5.setAA_BorderColor(new java.awt.Color(137, 100, 71));
        pH_Panel5.setAA_DrawBorder(true);
        pH_Panel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout pH_Panel5Layout = new javax.swing.GroupLayout(pH_Panel5);
        pH_Panel5.setLayout(pH_Panel5Layout);
        pH_Panel5Layout.setHorizontalGroup(
            pH_Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        pH_Panel5Layout.setVerticalGroup(
            pH_Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        pH_Label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label3.setText("DESCRIPTION");
        pH_Label3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        pH_Label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label9.setText("BUDGET");
        pH_Label9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pH_Label9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        pH_Button1.setBackground(new java.awt.Color(137, 100, 71));
        pH_Button1.setForeground(new java.awt.Color(255, 255, 255));
        pH_Button1.setText("SEND REQUEST");
        pH_Button1.setToolTipText("");
        pH_Button1.setAAA_ImageBoundArcSize(30);
        pH_Button1.setAAA_roundBottomLeft(30);
        pH_Button1.setAAA_roundBottomRight(30);
        pH_Button1.setAAA_roundTopLeft(30);
        pH_Button1.setAAA_roundTopRight(30);
        pH_Button1.setAA_ArcSize(30);
        pH_Button1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        pH_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pH_Button1ActionPerformed(evt);
            }
        });

        pH_Panel9.setBackground(new java.awt.Color(245, 240, 234));
        pH_Panel9.setAAA_ImageBoundArcSize(30);
        pH_Panel9.setAAA_roundBottomLeft(30);
        pH_Panel9.setAAA_roundBottomRight(30);
        pH_Panel9.setAAA_roundTopLeft(30);
        pH_Panel9.setAAA_roundTopRight(30);
        pH_Panel9.setAA_ArcSize(30);
        pH_Panel9.setAA_BorderColor(new java.awt.Color(137, 100, 71));
        pH_Panel9.setAA_DrawBorder(true);
        pH_Panel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout pH_Panel9Layout = new javax.swing.GroupLayout(pH_Panel9);
        pH_Panel9.setLayout(pH_Panel9Layout);
        pH_Panel9Layout.setHorizontalGroup(
            pH_Panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        pH_Panel9Layout.setVerticalGroup(
            pH_Panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jCalendar1.setBackground(new java.awt.Color(137, 100, 71));
        jCalendar1.setForeground(new java.awt.Color(137, 100, 71));
        jCalendar1.setDecorationBackgroundColor(new java.awt.Color(137, 100, 71));
        jCalendar1.setDecorationBackgroundVisible(false);
        jCalendar1.setSundayForeground(new java.awt.Color(137, 100, 71));
        jCalendar1.setWeekdayForeground(new java.awt.Color(137, 100, 71));

        javax.swing.GroupLayout pH_Panel3Layout = new javax.swing.GroupLayout(pH_Panel3);
        pH_Panel3.setLayout(pH_Panel3Layout);
        pH_Panel3Layout.setHorizontalGroup(
            pH_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pH_Panel3Layout.createSequentialGroup()
                .addGroup(pH_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pH_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pH_Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pH_Panel5, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                        .addComponent(pH_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                        .addComponent(pH_Label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pH_Panel9, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                        .addComponent(pH_Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                        .addComponent(pH_Label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pH_Label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pH_Panel3Layout.setVerticalGroup(
            pH_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pH_Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pH_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Panel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pH_Label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pH_Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pH_Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled design (41).png"))); // NOI18N

        javax.swing.GroupLayout ContentHolderLayout = new javax.swing.GroupLayout(ContentHolder);
        ContentHolder.setLayout(ContentHolderLayout);
        ContentHolderLayout.setHorizontalGroup(
            ContentHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pH_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ContentHolderLayout.createSequentialGroup()
                        .addComponent(pH_Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(pH_Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ContentHolderLayout.setVerticalGroup(
            ContentHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pH_Panel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContentHolderLayout.createSequentialGroup()
                        .addComponent(pH_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pH_Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pH_Panel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout RequestPageLayout = new javax.swing.GroupLayout(RequestPage);
        RequestPage.setLayout(RequestPageLayout);
        RequestPageLayout.setHorizontalGroup(
            RequestPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestPageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ContentHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        RequestPageLayout.setVerticalGroup(
            RequestPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestPageLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ContentHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RequestPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RequestPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pH_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pH_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pH_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Request().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SystemOtherComps.PH_Panel ContentHolder;
    private javax.swing.JPanel RequestPage;
    private com.toedter.calendar.JCalendar jCalendar1;
    private SystemOtherComps.PH_Button pH_Button1;
    private SystemOtherComps.PH_Label pH_Label1;
    private SystemOtherComps.PH_Label pH_Label2;
    private SystemOtherComps.PH_Label pH_Label3;
    private SystemOtherComps.PH_Label pH_Label4;
    private SystemOtherComps.PH_Label pH_Label5;
    private SystemOtherComps.PH_Label pH_Label6;
    private SystemOtherComps.PH_Label pH_Label7;
    private SystemOtherComps.PH_Label pH_Label8;
    private SystemOtherComps.PH_Label pH_Label9;
    private SystemOtherComps.PH_Panel pH_Panel1;
    private SystemOtherComps.PH_Panel pH_Panel2;
    private SystemOtherComps.PH_Panel pH_Panel3;
    private SystemOtherComps.PH_Panel pH_Panel4;
    private SystemOtherComps.PH_Panel pH_Panel5;
    private SystemOtherComps.PH_Panel pH_Panel6;
    private SystemOtherComps.PH_Panel pH_Panel7;
    private SystemOtherComps.PH_Panel pH_Panel8;
    private SystemOtherComps.PH_Panel pH_Panel9;
    // End of variables declaration//GEN-END:variables
}
