/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

/**
 *
 * @author iya
 */
public class CategoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form jPanel
     */
    public CategoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Image = new SystemOtherComps.PH_Panel();
        Number = new SystemOtherComps.PH_Label();
        Title = new SystemOtherComps.PH_Label();
        BG = new SystemOtherComps.PH_Label();

        Image.setBackground(new java.awt.Color(204, 255, 204));
        Image.setAAA_ImageBoundArcSize(10000);
        Image.setAAA_roundBottomLeft(50);
        Image.setAAA_roundBottomRight(50);
        Image.setAAA_roundTopLeft(50);
        Image.setAAA_roundTopRight(50);
        Image.setAA_ArcSize(1000000);
        Image.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Number.setBackground(new java.awt.Color(0, 0, 0));
        Number.setForeground(new java.awt.Color(255, 255, 255));
        Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Number.setText("03");
        Number.setAAA_roundBottomLeft(20);
        Number.setAAA_roundBottomRight(20);
        Number.setAAA_roundTopLeft(20);
        Number.setAAA_roundTopRight(20);
        Number.setAA_BorderColor(new java.awt.Color(0, 0, 0));
        Number.setAA_LabelColor(new java.awt.Color(255, 255, 255));
        Number.setAA_OpaqueBackground(false);
        Number.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Image.add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, 38, -1));

        Title.setForeground(new java.awt.Color(255, 245, 234));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Title.setText("Digital Art");
        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Image.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 87, 100, -1));

        BG.setForeground(new java.awt.Color(255, 245, 234));
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/try image.png"))); // NOI18N
        BG.setAAA_ImageBoundArcSize(50);
        BG.setAAA_roundBottomLeft(50);
        BG.setAAA_roundBottomRight(50);
        BG.setAAA_roundTopLeft(50);
        BG.setAAA_roundTopRight(50);
        BG.setAA_ArcSize(1000);
        BG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Image.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Image, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Image, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SystemOtherComps.PH_Label BG;
    private SystemOtherComps.PH_Panel Image;
    private SystemOtherComps.PH_Label Number;
    private SystemOtherComps.PH_Label Title;
    // End of variables declaration//GEN-END:variables
}
