/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

/**
 *
 * @author iya
 */
public class morePanel extends javax.swing.JPanel {

    /**
     * Creates new form morePanel
     */
    public morePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pH_Panel1 = new SystemOtherComps.PH_Panel();
        more = new SystemOtherComps.PH_Label();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pH_Panel1.setBackground(new java.awt.Color(72, 53, 40));
        pH_Panel1.setOpaque(true);

        more.setBackground(new java.awt.Color(255, 255, 255));
        more.setForeground(new java.awt.Color(255, 245, 234));
        more.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        more.setText("More >");
        more.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout pH_Panel1Layout = new javax.swing.GroupLayout(pH_Panel1);
        pH_Panel1.setLayout(pH_Panel1Layout);
        pH_Panel1Layout.setHorizontalGroup(
            pH_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pH_Panel1Layout.createSequentialGroup()
                .addComponent(more, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
        pH_Panel1Layout.setVerticalGroup(
            pH_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pH_Panel1Layout.createSequentialGroup()
                .addComponent(more, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );

        add(pH_Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SystemOtherComps.PH_Label more;
    private SystemOtherComps.PH_Panel pH_Panel1;
    // End of variables declaration//GEN-END:variables
}
