/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author elain
 */
public class PaymentPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentPanel
     */
    public PaymentPanel() {
        initComponents();
        this.setPreferredSize(new java.awt.Dimension(1280, 720));
        this.setSize(1280, 720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUserInfo = new javax.swing.JPanel();
        panelArtQty = new javax.swing.JPanel();
        panelPaymentMethod = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(120, 120));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUserInfo.setPreferredSize(new java.awt.Dimension(1280, 150));

        javax.swing.GroupLayout panelUserInfoLayout = new javax.swing.GroupLayout(panelUserInfo);
        panelUserInfo.setLayout(panelUserInfoLayout);
        panelUserInfoLayout.setHorizontalGroup(
            panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        panelUserInfoLayout.setVerticalGroup(
            panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(panelUserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout panelArtQtyLayout = new javax.swing.GroupLayout(panelArtQty);
        panelArtQty.setLayout(panelArtQtyLayout);
        panelArtQtyLayout.setHorizontalGroup(
            panelArtQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelArtQtyLayout.setVerticalGroup(
            panelArtQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(panelArtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        javax.swing.GroupLayout panelPaymentMethodLayout = new javax.swing.GroupLayout(panelPaymentMethod);
        panelPaymentMethod.setLayout(panelPaymentMethodLayout);
        panelPaymentMethodLayout.setHorizontalGroup(
            panelPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelPaymentMethodLayout.setVerticalGroup(
            panelPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(panelPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelArtQty;
    private javax.swing.JPanel panelPaymentMethod;
    private javax.swing.JPanel panelUserInfo;
    // End of variables declaration//GEN-END:variables
}
