/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

/**
 *
 * @author JM Uayan
 */
public class PortfolioPanel extends javax.swing.JPanel {

    /**
     * Creates new form PortfolioPanel
     */
    public PortfolioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pH_Panel5 = new SystemOtherComps.PH_Panel();
        pH_TextField4 = new SystemOtherComps.PH_TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pH_Panel5.setBackground(new java.awt.Color(245, 240, 234));
        pH_Panel5.setAAA_ImageBoundArcSize(30);
        pH_Panel5.setAAA_roundBottomLeft(30);
        pH_Panel5.setAAA_roundBottomRight(30);
        pH_Panel5.setAAA_roundTopLeft(30);
        pH_Panel5.setAAA_roundTopRight(30);
        pH_Panel5.setAA_ArcSize(30);
        pH_Panel5.setAA_BorderColor(new java.awt.Color(137, 100, 71));
        pH_Panel5.setAA_DrawBorder(true);
        pH_Panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pH_TextField4.setEditable(false);
        pH_TextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pH_TextField4.setText("ELAIZA O. BUGAYONG ");
        pH_TextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pH_TextField4ActionPerformed(evt);
            }
        });
        pH_Panel5.add(pH_TextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 36, 285, 68));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(247, 235, 221));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ornare enim sed lectus pulvinar venenatis. Vestibulum in dolor ullamcorper, mollis tortor ut, suscipit purus.");
        jScrollPane1.setViewportView(jTextArea1);

        pH_Panel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 122, 425, -1));

        add(pH_Panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 52, 487, 225));
    }// </editor-fold>//GEN-END:initComponents

    private void pH_TextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pH_TextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pH_TextField4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private SystemOtherComps.PH_Panel pH_Panel5;
    private SystemOtherComps.PH_TextField pH_TextField4;
    // End of variables declaration//GEN-END:variables
}
