/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

/**
 *
 * @author iya
 */
public class Sculpture extends javax.swing.JPanel {

    /**
     * Creates new form jPanel
     */
    public Sculpture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Image = new SystemOtherComps.PH_Panel();
        Number = new SystemOtherComps.PH_Label();
        Title = new SystemOtherComps.PH_Label();

        Image.setBackground(new java.awt.Color(204, 255, 204));
        Image.setAAA_ImageBoundArcSize(10000);
        Image.setAAA_roundBottomLeft(50);
        Image.setAAA_roundBottomRight(50);
        Image.setAAA_roundTopLeft(50);
        Image.setAAA_roundTopRight(50);
        Image.setAA_ArcSize(1000000);

        Number.setBackground(new java.awt.Color(0, 0, 0));
        Number.setForeground(new java.awt.Color(255, 255, 255));
        Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Number.setText("02");
        Number.setAAA_roundBottomLeft(20);
        Number.setAAA_roundBottomRight(20);
        Number.setAAA_roundTopLeft(20);
        Number.setAAA_roundTopRight(20);
        Number.setAA_BorderColor(new java.awt.Color(0, 0, 0));
        Number.setAA_LabelColor(new java.awt.Color(255, 255, 255));
        Number.setAA_OpaqueBackground(false);
        Number.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Title.setText("Sculpture");
        Title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout ImageLayout = new javax.swing.GroupLayout(Image);
        Image.setLayout(ImageLayout);
        ImageLayout.setHorizontalGroup(
            ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ImageLayout.createSequentialGroup()
                        .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ImageLayout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(132, 132, 132))))
        );
        ImageLayout.setVerticalGroup(
            ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImageLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Image, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Image, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SystemOtherComps.PH_Panel Image;
    private SystemOtherComps.PH_Label Number;
    private SystemOtherComps.PH_Label Title;
    // End of variables declaration//GEN-END:variables
}
