/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

/**
 *
 * @author iya
 */
public class TimelessPanel extends javax.swing.JPanel {

    /**
     * Creates new form jPanel
     */
    public TimelessPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pH_Panel1 = new SystemOtherComps.PH_Panel();
        pH_Label1 = new SystemOtherComps.PH_Label();
        pH_Label2 = new SystemOtherComps.PH_Label();
        pH_Label3 = new SystemOtherComps.PH_Label();

        pH_Panel1.setBackground(new java.awt.Color(153, 255, 153));
        pH_Panel1.setAAA_roundBottomLeft(50);
        pH_Panel1.setAAA_roundBottomRight(50);
        pH_Panel1.setAAA_roundTopLeft(50);
        pH_Panel1.setAAA_roundTopRight(50);

        pH_Label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label1.setText("TIMELESS ART");
        pH_Label1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        pH_Label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label2.setText("Whether you love modern minimalism,  timeless classics, ");
        pH_Label2.setToolTipText("");
        pH_Label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pH_Label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pH_Label3.setText("or bold statement pieces.");
        pH_Label3.setToolTipText("");
        pH_Label3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout pH_Panel1Layout = new javax.swing.GroupLayout(pH_Panel1);
        pH_Panel1.setLayout(pH_Panel1Layout);
        pH_Panel1Layout.setHorizontalGroup(
            pH_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pH_Panel1Layout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addGroup(pH_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pH_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pH_Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pH_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pH_Label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pH_Panel1Layout.setVerticalGroup(
            pH_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pH_Panel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(pH_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pH_Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pH_Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pH_Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SystemOtherComps.PH_Label pH_Label1;
    private SystemOtherComps.PH_Label pH_Label2;
    private SystemOtherComps.PH_Label pH_Label3;
    private SystemOtherComps.PH_Panel pH_Panel1;
    // End of variables declaration//GEN-END:variables
}
