/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

/**
 *
 * @author iya
 */
public class TimelessPanel extends javax.swing.JPanel {

    /**
     * Creates new form jPanel
     */
    public TimelessPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pH_Panel1 = new SystemOtherComps.PH_Panel();
        Title = new SystemOtherComps.PH_Label();
        D1 = new SystemOtherComps.PH_Label();
        D2 = new SystemOtherComps.PH_Label();
        White_BG = new SystemOtherComps.PH_Label();
        Background_image = new SystemOtherComps.PH_Label();

        pH_Panel1.setBackground(new java.awt.Color(153, 255, 153));
        pH_Panel1.setAAA_roundBottomLeft(50);
        pH_Panel1.setAAA_roundBottomRight(50);
        pH_Panel1.setAAA_roundTopLeft(50);
        pH_Panel1.setAAA_roundTopRight(50);
        pH_Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setForeground(new java.awt.Color(72, 53, 40));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Title.setText("TIMELESS ART");
        Title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        pH_Panel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 473, 81));

        D1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D1.setText("Whether you love modern minimalism,  timeless classics, ");
        D1.setToolTipText("");
        D1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pH_Panel1.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 179, 473, 18));

        D2.setForeground(new java.awt.Color(72, 53, 40));
        D2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D2.setText("or bold statement pieces.");
        D2.setToolTipText("");
        D2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pH_Panel1.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 203, 473, 18));

        White_BG.setBackground(new java.awt.Color(255, 238, 219));
        White_BG.setForeground(new java.awt.Color(0, 0, 0));
        White_BG.setToolTipText("");
        White_BG.setOpaque(true);
        pH_Panel1.add(White_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 500, 350));

        Background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/try image.png"))); // NOI18N
        pH_Panel1.add(Background_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 903, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pH_Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pH_Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SystemOtherComps.PH_Label Background_image;
    private SystemOtherComps.PH_Label D1;
    private SystemOtherComps.PH_Label D2;
    private SystemOtherComps.PH_Label Title;
    private SystemOtherComps.PH_Label White_BG;
    private SystemOtherComps.PH_Panel pH_Panel1;
    // End of variables declaration//GEN-END:variables
}
